[build]
  command = "npm run build"

[[redirects]]
  from = "https://docs.zitadel.ch/docs/legal/*"
  to = "https://docs.zitadel.com/docs/legal/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/proxy/js/script.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200
  force = true

[[redirects]]
  from = "/proxy/api/event"
  to = "https://plausible.io/api/event"
  status = 202
  force = true
  
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
	  max-age=31536000;
	  includeSubDomains;
	  preload'''
    
