name: Docs
on:
  push:
    paths:
      - 'site/**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  builddocs:
    name: Build Doc Frontend
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./site
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./site/dockerfile
        platforms: linux/amd64
        tags: zitadel:docs
        push: false
        outputs: type=local,dest=output
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: export
        path: output
  deploydocs:
    name: Deploy
    needs: builddocs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: export
          path: site/__sapper__/export
      - name: Add CNAME file
        run: echo "docs.zitadel.ch" > site/__sapper__/export/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site/__sapper__/export
          CLEAN: true